version: '2.1'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "tgsup"
      POSTGRES_PASSWORD: "tgsup"
      POSTGRES_DB: "tgsup"
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
